### ISSUE TITLE
A good start

### ISSUE THREAD

**Issue by freeidiot40x2** [christiankyle-ching/DigitalWellbeingForWindows#1]
Hi there,

This is definitely a welcome program for Windows since we definitely need something to monitor how long we spend in front of our screens. A few quick questions/suggestions:

1. Will there be an option to block an app after a few minutes/hours/custom time, similar to the focus mode in Android (Samsung)? Even a popup alert that I have spent "so many hours/minutes" on this app would be great.

2. Clicking on "Excluded Apps" closes the program. Would this be fixed? 

Thanks.

**Comment by christiankyle-ching** [comment]
1. Blocking an app is not yet planned. Notification popup is possible in the future.
2. This is definitely a bug. Can you provide the step-by-step procedure to replicate this behavior? Does it always happen or only sometimes?

**Comment by freeidiot40x2** [comment]
> 1. Blocking an app is not yet planned. Notification popup is possible in the future.
> 
>     2. This is definitely a bug. Can you provide the step-by-step procedure to replicate this behavior? Does it always happen or only sometimes?

I open the program, click on "settings", then click on the blank white box, next to "Excluded Apps", this results in the program closing itself.

**Comment by christiankyle-ching** [comment]
Forgot to try..catch when no item is selected.

Fixed in: 378067da0017889f544906c396b4ac011c19ee65

**Comment by christiankyle-ching** [comment]
@freeidiot40x2 Alert Notifications, Auto Run on Startup, and Global Exception Handling (with direct report here in Github) are now available in latest release.

https://github.com/christiankyle-ching/DigitalWellbeingForWindows/releases/tag/v1.0.5.0

Thanks.
