### ISSUE TITLE
Randomly stopped Tracking

### ISSUE THREAD

**Issue by lupleime** [christiankyle-ching/DigitalWellbeingForWindows#3]
When i got home from why i had my pc running and now i wont track any progress anymore even after resetting

![image](https://user-images.githubusercontent.com/43088999/171265576-0b6ccc55-c4ed-450f-9eea-d6e17eec6358.png)

**Comment by christiankyle-ching** [comment]
Can you check your `Task Manager > Startup` and see if the `DigitalWellbeingService.NET4.6` is `Enabled`? If not, then `Right Click > Enable` to enable it from startup.

`DigitalWellbeingService.NET4.6.exe` is the one that's tracking your app usage.

![image](https://user-images.githubusercontent.com/57316283/171304165-b4b7f7cc-910e-4b49-ac76-4e8b7e5e8954.png)
