### ISSUE TITLE
Daily logs saved but only able to view last 7 days in app

### ISSUE THREAD

**Issue by Some1sm** [christiankyle-ching/DigitalWellbeingForWindows#6]
So I've been using the program for a few months and it's incredible tbh, but I realized I can only see the last 7 days of usage unless I'm missing something.

Daily logs have been saved for all this time but cannot be viewed inside the program. Is it intended? 

I will attach a photo of the GUI to see if you guys can guide me to where I could see this info lol
![image_2023-04-07_222753939](https://user-images.githubusercontent.com/27234082/230674609-ed5dfb06-0485-42b2-9e5f-f73035f85a1b.png)

Also proof that logs are saved after those 7 days
![image_2023-04-07_222824873](https://user-images.githubusercontent.com/27234082/230674677-04139813-1c10-49f9-af7a-8925fd972b14.png)

If you don't update this I swear I will learn to code and update it myself 😂 addicted to keeping track of the things I do.

**Comment by amit-arora15** [comment]
+1 

There should be an option to view previous days.  Please update it. @Some1sm

**Comment by kashi618** [comment]
+1
An option to toggle between even (last 7 days, last week, last month, overall/all) would be nice.

**Comment by Some1sm** [comment]
Sadly AI's aren't smart enough to help me code this lol I only have Java basic knowledge. If you guys hang around for one more year or so I might be able to code it XD

**Comment by Some1sm** [comment]
@kashi618 @amit-arora15 
https://github.com/Some1sm/DigitalWellbeingForWindows/releases/tag/Release

There you go. Google Gemini for the win. I don't even know how to code so I'm amazed this worked lol
